plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
theme: minima
include:
  - 2022-04-21-home.md
  - 2022-04-21-bush-gas-dream-gas.md
  - 2022-04-21-microbiome.md
  - 2022-04-21-poems-from-experience.md
  - 2022-04-22-power-outage.md
  - index.html
  - _posts
